version: '3'
services:
  proxy:
    image: mahdilotfi/nsproxy:latest
    restart: always
    ports:
      - "1053:53/udp"
    volumes:
      - ./config.json:/etc/nsproxy.json
  cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
